Change boot option to manual_only
hacs/addons pull request #11
Opened 2024-09-05 09:10 UTC by tjorim

Add-on should never start at boot, prevents users from changing it. https://github.com/home-assistant/supervisor/pull/5272

2024-09-05 09:13 UTC, ludeeus commented
Why should it not?

Personally i have it to start on boot to grab the latest dev build.

2024-09-05 09:20 UTC, tjorim commented
I guess that's a valid use case but aren't you always running a version behind that way? Does `startup: once` ensure the add-on runs before HA? When you reboot your system, HA starts, add-on runs and pulls the latest version. Don't you need to restart HA itself again to make it active?

2024-09-05 09:24 UTC, ludeeus commented
Hmmm.... good point, maybe mu use-case is flawed 😄

2024-09-05 18:01 UTC, ludeeus commented
Okey, it was flawed.
So this should probably be included.
But will have to wait until then supervisor has been released to stable (and the linger support it).

2024-12-18 16:40 UTC, ludeeus commented on get/config.yaml
> +boot: manual_only
Do you know of any (official?) add-ons that have had a similar change?
Im curious about what will happen to those who have set this toggle previously.

2025-01-05 08:57 UTC, ludeeus commented on get/config.yaml
> +boot: manual_only
Tested it, does not seem to impact much.
Personally I don't like that the option is still in the UI when this is set like this, but that is a different topic.

2025-01-05 08:57 UTC, ludeeus requested changes
The version should be bumped to 1.3.2 and an entry in the changelog is needed.

2026-02-19 12:17 UTC, closed without merging